# Generated by Django 3.2.4 on 2021-06-23 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hptl', '0002_auto_20210623_0557'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
