# Generated by Django 3.2.4 on 2021-06-23 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hptl', '0004_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='num',
            field=models.IntegerField(),
        ),
    ]
